import MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility

open MaleyLean

#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperPhysicalBellOccurrenceNeedsWitnessRoleStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNDBellWitnessForcesFixedScopeStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperBoundaryLevelCompatibilityStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperBellWitnessTraceFixationStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperJointStandingClassStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperTensorCompatibilityStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperAMetricCoStandingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperLocalRealizationFacesStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoSignalingEndpointStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoSameDomainSignalTypingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoMetricTransportTypingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoMarginalModulationTypingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoDistantRepairTypingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoHiddenLocalAuthorizerTypingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoDelayedCalibrationRepairTypingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoExtraDiscriminatorTypingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperFailClosedWithoutBoundaryCompatibilityStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperBellWitnessBoundaryCompatibilityAndNoSignalingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperQuantumDeterminacyPairBellSideStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.Surface.SummaryStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.Surface.PairedQuantumDeterminacySummaryStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperFiniteOperationalDynamicsProducesBellOccurrenceStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperFiniteOperationalDynamicsProducesNDBellWitnessStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperBornProfileForcesTensorCompatibilityStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoSignalingMarginalsForbidMarginalModulationStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperTensorPreparationGivesJointStandingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperOperationalDynamicsBoundaryCompatibilityStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperOperationalDynamicsNoSignalingEndpointStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperOperationalDynamicsInstantiatesBellWitnessSurfaceStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperOperationalDynamicsKernelCertificateStatement
