import MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility
import MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.FiniteGeometryProfile

open MaleyLean

#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperPhysicalBellOccurrenceNeedsWitnessRoleStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNDBellWitnessForcesFixedScopeStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperBoundaryLevelCompatibilityStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperBellWitnessTraceFixationStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperJointStandingClassStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperTensorCompatibilityStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperAMetricCoStandingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperLocalRealizationFacesStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoSignalingEndpointStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoSameDomainSignalTypingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoMetricTransportTypingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoMarginalModulationTypingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoDistantRepairTypingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoHiddenLocalAuthorizerTypingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoDelayedCalibrationRepairTypingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoExtraDiscriminatorTypingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperFailClosedWithoutBoundaryCompatibilityStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperBellWitnessBoundaryCompatibilityAndNoSignalingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperQuantumDeterminacyPairBellSideStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.Surface.SummaryStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.Surface.PairedQuantumDeterminacySummaryStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperFiniteOperationalDynamicsProducesBellOccurrenceStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperFiniteOperationalDynamicsProducesNDBellWitnessStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperBornProfileForcesTensorCompatibilityStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperNoSignalingMarginalsForbidMarginalModulationStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperTensorPreparationGivesJointStandingStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperOperationalDynamicsBoundaryCompatibilityStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperOperationalDynamicsNoSignalingEndpointStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperOperationalDynamicsInstantiatesBellWitnessSurfaceStatement
#print axioms Papers.QuantumEntanglementBoundaryCompatibility.PaperOperationalDynamicsKernelCertificateStatement
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.concreteCHSH_normalized32
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.concreteCHSH_alice_no_signaling32
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.concreteCHSH_bob_no_signaling32
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.concreteCHSH_value32
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.concreteCHSH_exceeds_classical_bound_by_gap32
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.concreteCHSH_derived_facts
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.deterministicCHSHRaw_is_plus_or_minus_two
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.deterministicBellLocalBound32
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.concreteCHSH_exceeds_bell_local_envelope
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.singletBornWeight_matches_concreteCHSHWeight32
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.singletBorn_table_normalized32
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.singletBorn_alice_no_signaling32
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.singletBorn_bob_no_signaling32
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.singletBorn_derives_concreteCHSH_table
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.singletBorn_derives_bell_local_gap
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.finite_axis_singlet_correlation_matches_profile
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.axisBornWeight_matches_singletBornWeight32
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.axisBornWeight_matches_concreteCHSHWeight32
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.axisBorn_table_normalized32
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.axisBorn_alice_no_signaling32
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.axisBorn_bob_no_signaling32
#print axioms MaleyLean.Papers.QuantumEntanglementBoundaryCompatibility.finiteAxisGeometry_derives_singletBorn_profile
